In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [9]:
df=sns.load_dataset("mpg")

In [10]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [11]:
df.isna().sum()

,0
mpg,0
cylinders,0
displacement,0
horsepower,6
weight,0
acceleration,0
model_year,0
origin,0
name,0


In [12]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000


In [13]:
df.dtypes

,0
mpg,float64
cylinders,int64
displacement,float64
horsepower,float64
weight,int64
acceleration,float64
model_year,int64
origin,object
name,object


In [14]:
df.drop("name",axis=1,inplace=True)

In [15]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa


In [16]:
df["horsepower"].median()

93.5

In [17]:
df["horsepower"]=df["horsepower"].fillna(df["horsepower"].median())

In [18]:
df.isna().sum()

,0
mpg,0
cylinders,0
displacement,0
horsepower,0
weight,0
acceleration,0
model_year,0
origin,0


In [19]:
df['origin'].value_counts()

,count
origin,
usa,249
japan,79
europe,70


In [20]:
df['origin']=df['origin'].map({'usa':1,'europe':2,'japan':3})

In [21]:
 x=df.drop("mpg",axis=1)
 y=df['mpg']

In [22]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,2
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1


In [23]:
y

,mpg
0,18.0
1,15.0
2,18.0
3,16.0
4,17.0
...,...
393,27.0
394,44.0
395,32.0
396,28.0


In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [26]:
x_train.shape

(318, 7)

In [27]:
x_test.shape

(80, 7)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [ ]:
model

LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.coef_

array([-0.27836591,  0.01793853, -0.01589565, -0.00670971,  0.1081923 ,
        0.79373357,  1.33397416])

In [ ]:
model.intercept_

np.float64(-20.969906729771512)

In [ ]:
from sklearn.metrics import r2_score
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)
#

0.8641210527455927

In [ ]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=0.1)
ridge_model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [ ]:
y_pred_ridge=ridge_model.predict(x_test)
r2_score(y_test,y_pred_ridge)

0.8641130217509363

In [ ]:
from sklearn.linear_model import Lasso
lasso_model=Lasso(alpha=0.5)

In [ ]:
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.5)

In [ ]:
y_pred_lasso=lasso_model.predict(x_test)
r2_score(y_test,y_pred_lasso)

0.8457765614927952

In [ ]:
lasso_model.coef_

array([-0.        ,  0.00197727, -0.00929169, -0.00658993,  0.        ,
        0.75320801,  0.        ])

In [ ]:
from sklearn.linear_model import ElasticNet
elastic_model=ElasticNet(alpha=1,l1_ratio=0.5)

In [ ]:
elastic_model.fit(x_train,y_train)

ElasticNet(alpha=1)

In [ ]:
elastic_model.coef_

array([-0.        ,  0.0015385 , -0.01064196, -0.00653261,  0.        ,
        0.72035415,  0.        ])

In [ ]:
y_pred_elastic=elastic_model.predict(x_test)
r2_score(y_test,y_pred_elastic)
#

0.8477301010951965

In [1]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [2]:
lasso_model=Lasso()

In [3]:
lasso_model

Lasso()

In [4]:
param_grid={"alpha":[0.001,0.01,0.1,1,10,100]}

In [6]:
grid_search=GridSearchCV(estimator=lasso_model,param_grid=param_grid,cv=5,scoring="r2",verbose=2)

In [7]:
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [28]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [29]:
grid_search.best_params_

{'alpha': 0.1}

In [30]:
grid_search.best_score_

np.float64(0.7962757287599538)

In [31]:
grid_search.best_estimator_

Lasso(alpha=0.1)

In [35]:
y_pred=grid_search.best_estimator_.predict(x_test)

In [36]:
from sklearn.metrics import r2_score

In [37]:
r2_score(y_test,y_pred)

0.8602497881228282

In [38]:
ridge=Ridge()

In [40]:
random_search=RandomizedSearchCV(estimator=ridge,param_distributions=param_grid,cv=5,scoring="r2",verbose=2)

In [41]:
random_search

RandomizedSearchCV(cv=5, estimator=Ridge(),
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [42]:
random_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

RandomizedSearchCV(cv=5, estimator=Ridge(),
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [43]:
random_search.best_estimator_

Ridge(alpha=10)

In [44]:
random_search.best_params_

{'alpha': 10}

In [45]:
y_pred=random_search.best_estimator_.predict(x_test)

In [46]:
r2_score(y_test,y_pred)

0.8633254814863351

In [47]:
ridge=Ridge()

In [50]:
grid_search=GridSearchCV(estimator=ridge,param_grid=param_grid,cv=5,scoring="r2",verbose=2)

In [51]:
grid_search

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [52]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [53]:
y_pred=grid_search.best_estimator_.predict(x_test)

In [54]:
r2_score(y_test,y_pred)

0.8633254814863351

In [57]:
random_search=RandomizedSearchCV(estimator=lasso_model,param_distributions=param_grid,cv=5,scoring="r2",verbose=2)

In [58]:
random_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

RandomizedSearchCV(cv=5, estimator=Lasso(),
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [59]:
y_pred=random_search.best_estimator_.predict(x_test)

In [60]:
r2_score(y_test,y_pred)

0.8602497881228282

In [61]:
param_grid={"alpha":[0.001,0.01,0.1,1,10,100],"l1_ratio":[0.1,0.4,0.9]}

In [62]:
model=ElasticNet()
grid_search=GridSearchCV(estimator=model,param_grid=param_grid,cv=5,scoring="r2",verbose=2)
grid_search.fit(x_train,y_train)
y_pred=grid_search.best_estimator_.predict(x_test)
r2_score(y_test,y_pred)
#

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, 

0.8602303901930302